version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./install:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h mysql -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5

  ecommerce:
    build: ./server_configs/ecommerce
    container_name: buckedup.local
    expose:   
      - 80
    environment:
      - VIRTUAL_HOST=buckedup.local
    depends_on:
      - php
      - mysql
    volumes_from:
      - php  

  bootcamp:
    build: ./server_configs/bootcamp
    container_name: bootcamp.local
    expose:   
      - 80
    environment:
      - VIRTUAL_HOST=bootcamp.local
    depends_on:
      - php
      - mysql
    volumes_from:
      - php

  brandloudr:
    build: ./server_configs/brandloudr
    container_name: brandloudr.local
    expose:   
      - 80
    environment:
      - VIRTUAL_HOST=brandloudr.local
    depends_on:
      - php
      - mysql
    volumes_from:
      - php

  test:
    build: ./server_configs/test
    container_name: test.local
    expose:   
      - 80
    environment:
      - VIRTUAL_HOST=test.local
    depends_on:
      - php
      - mysql
    volumes_from:
      - php      
      
  php:
    build: ./server_configs/php/
    container_name: Bucked_Up_PHP
    expose:
      - 9000
    volumes:
      - ${PATH_TO_PROJECT_DIR}:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD-SHELL", "php -v"]
      interval: 10s
      retries: 5

  phpmyadmin:
    container_name: phpmyadmin.local
    image: phpmyadmin
    restart: always
    expose:
      - 80
    environment:
      - PMA_ARBITRARY=1
      - VIRTUAL_HOST=phpmyadmin.local

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

volumes:
  mysql-data:
